# Site settings
baseurl = "https://kfrankc.com"
languageCode = "en-us"
sectionPagesMenu = "main"
googleAnalytics = "UA-128201385-1"

[params]
	name = "Frank Chen"
  title = "Frank Chen"
	description = "PM @ Microsoft"
	email = "kfrankc@uw.edu"
	author = "kfrankc"
	copyrightname = "Frank Chen"
  images = [""]

[taxonomies]
  series = "series"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "rainbow_dash"
    tabWidth = 4